name: Unit testing
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          maven-version: 8
      - name: Build Maven
        run: mvn '-Dtest=es.codeurjc.daw.unitary.*Test'
     